## Datensammlung: BFS-Hotellerie (Tabellen 201 und 101), Wetter, Geodaten.

In [5]:
import requests, json, pathlib

BASE = "https://www.pxweb.bfs.admin.ch/api/v1/de/px-x-1003020000_{t}/px-x-1003020000_{t}.px"
RAW = pathlib.Path("../data/raw/bfs"); RAW.mkdir(parents=True, exist_ok=True)

for t in ["201", "101"]:
    meta = requests.get(BASE.format(t=t), timeout=30).json()
    (RAW / f"meta_{t}.json").write_text(json.dumps(meta, ensure_ascii=False, indent=1), encoding="utf-8")
    print("Tabelle", t, "-", meta["title"])
    for v in meta["variables"]:
        print(f"  {v['code']:<14} {len(v['values']):>4} Werte   z.B. {v['valueTexts'][:4]}")

print()
print("--- Codes ---")
for t in ["201", "101"]:
    meta = json.loads((RAW / f"meta_{t}.json").read_text(encoding="utf-8"))
    print("Tabelle", t)
    for v in meta["variables"]:
        if v["code"] in ("Indikator", "Monat", "Herkunftsland"):
            print(" ", v["code"], list(zip(v["values"], v["valueTexts"]))[:15])

Tabelle 201 - Hotellerie: Angebot und Nachfrage der geöffneten Betriebe nach Jahr, Monat, Gemeinde und Indikator
  Jahr             14 Werte   z.B. ['2013', '2014', '2015', '2016']
  Monat            13 Werte   z.B. ['Jahrestotal', 'Januar', 'Februar', 'März']
  Gemeinde        186 Werte   z.B. ['Kloten', 'Opfikon', 'Dübendorf', 'Uster']
  Indikator         8 Werte   z.B. ['Betriebe', 'Zimmer', 'Betten', 'Ankünfte']
Tabelle 101 - Hotellerie: Ankünfte und Logiernächte der geöffneten Betriebe nach Jahr, Monat, Gemeinde, Herkunftsland und Indikator
  Jahr             14 Werte   z.B. ['2013', '2014', '2015', '2016']
  Monat            13 Werte   z.B. ['Jahrestotal', 'Januar', 'Februar', 'März']
  Gemeinde        186 Werte   z.B. ['Kloten', 'Opfikon', 'Dübendorf', 'Uster']
  Herkunftsland    73 Werte   z.B. ['Herkunftsland - Total', 'Schweiz', 'Deutschland', 'Frankreich']
  Indikator         2 Werte   z.B. ['Ankünfte', 'Logiernächte']

--- Codes ---
Tabelle 201
  Monat [('YYYY', 'Jahrestotal'), ('1', 'Januar'), ('2', 'Februar'), ('3', 'März'), ('4', 'April'), ('5', 'Mai'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'August'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Dezember')]
  Indikator [('1', 'Betriebe'), ('2', 'Zimmer'), ('3', 'Betten'), ('4', 'Ankünfte'), ('5', 'Logiernächte'), ('6', 'Zimmernächte'), ('7', 'Zimmerauslastung in %'), ('8', 'Bettenauslastung in %')]
Tabelle 101
  Monat [('YYYY', 'Jahrestotal'), ('1', 'Januar'), ('2', 'Februar'), ('3', 'März'), ('4', 'April'), ('5', 'Mai'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'August'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Dezember')]
  Herkunftsland [('0', 'Herkunftsland - Total'), ('1', 'Schweiz'), ('11', 'Deutschland'), ('13', 'Frankreich'), ('14', 'Italien'), ('15', 'Österreich'), ('16', 'Vereinigtes Königreich'), ('17', 'Irland'), ('18', 'Niederlande'), ('19', 'Belgien'), ('20', 'Luxemburg'), ('21', 'Dänemark'), ('22', 'Schweden'), ('23', 'Norwegen'), ('24', 'Finnland')]
  Indikator [('1', 'Ankünfte'), ('2', 'Logiernächte')]

In [6]:
meta = json.loads((RAW / "meta_201.json").read_text(encoding="utf-8"))
ind = next(v for v in meta["variables"] if v["code"] == "Indikator")
for code, text in zip(ind["values"], ind["valueTexts"]):
    print(code, text)

1 Betriebe
2 Zimmer
3 Betten
4 Ankünfte
5 Logiernächte
6 Zimmernächte
7 Zimmerauslastung in %
8 Bettenauslastung in %

## 2. Hotellerie-Daten (Tabelle 201)

In [7]:
   import requests, json, time, pathlib
   import pandas as pd

   BASE = "https://www.pxweb.bfs.admin.ch/api/v1/de/px-x-1003020000_{t}/px-x-1003020000_{t}.px"
   RAW = pathlib.Path("../data/raw/bfs")
   meta = json.loads((RAW / "meta_201.json").read_text(encoding="utf-8"))
   gemeinden = next(v for v in meta["variables"] if v["code"] == "Gemeinde")["values"]

   def fetch_201(jahr):
       query = {
           "query": [
               {"code": "Jahr",      "selection": {"filter": "item", "values": [str(jahr)]}},
               {"code": "Monat",     "selection": {"filter": "item", "values": [str(m) for m in range(1, 13)]}},
               {"code": "Gemeinde",  "selection": {"filter": "item", "values": gemeinden}},
               {"code": "Indikator", "selection": {"filter": "item", "values": ["2","3","5","6","7","8"]}},
           ],
           "response": {"format": "json"},
       }
       r = requests.post(BASE.format(t="201"), json=query, timeout=60)
       r.raise_for_status()
       return r.json()

   for jahr in range(2013, 2027):
       ziel = RAW / f"hesta_201_{jahr}.json"
       if ziel.exists():
           continue                      # schon geladen -> überspringen
       data = fetch_201(jahr)
       ziel.write_text(json.dumps(data), encoding="utf-8")
       print(jahr, len(data["data"]), "Zeilen")
       time.sleep(2)                     # Server schonen

2013 13392 Zeilen
2014 13392 Zeilen
2015 13392 Zeilen
2016 13392 Zeilen
2017 13392 Zeilen
2018 13392 Zeilen
2019 13392 Zeilen
2020 13392 Zeilen
2021 13392 Zeilen
2022 13392 Zeilen
2023 13392 Zeilen
2024 13392 Zeilen
2025 13392 Zeilen
2026 13392 Zeilen

In [8]:
   rows = []
   for f in sorted(RAW.glob("hesta_201_*.json")):
       for d in json.loads(f.read_text(encoding="utf-8"))["data"]:
           rows.append(d["key"] + d["values"])          # [Jahr, Monat, Gemeinde, Indikator, Wert]
   df = pd.DataFrame(rows, columns=["jahr", "monat", "bfs_nr", "indikator", "wert"])
   df["wert"] = pd.to_numeric(df["wert"], errors="coerce")   # "..." -> NaN
   namen = {"2":"zimmer","3":"betten","5":"logiernaechte","6":"zimmernaechte",
            "7":"zimmerauslastung","8":"bettenauslastung"}
   df["indikator"] = df["indikator"].map(namen)
   hotel = df.pivot_table(index=["bfs_nr","jahr","monat"], columns="indikator",
                          values="wert", aggfunc="first").reset_index()
   hotel[["bfs_nr","jahr","monat"]] = hotel[["bfs_nr","jahr","monat"]].astype(int)
   hotel.to_csv("../data/processed/hotellerie_monat.csv", index=False)
   print(hotel.shape); hotel.head()

(29459, 9)

indikator,bfs_nr,jahr,monat,betten,bettenauslastung,logiernaechte,zimmer,zimmerauslastung,zimmernaechte
0,1024,2013,1,310.0,18.0,1737.0,175.0,22.0,1181.0
1,1024,2013,10,310.0,29.0,2760.0,175.0,44.0,2364.0
2,1024,2013,11,310.0,24.0,2186.0,175.0,35.0,1830.0
3,1024,2013,12,310.0,20.0,1882.0,175.0,30.0,1575.0
4,1024,2013,2,310.0,19.0,1684.0,175.0,31.0,1504.0

In [9]:
   print(hotel.shape)                         # max. 186 x 12 x 14 = 31'248 Zeilen
   print(hotel.isna().sum())                  # fehlende Werte pro Spalte, Zahl notieren
   print(hotel.describe().round(1))           # zimmerauslastung muss zwischen 0 und 100 liegen
   print(sorted(hotel["jahr"].unique()))      # 2013 bis 2026

(29459, 9)
indikator
bfs_nr               0
jahr                 0
monat                0
betten               0
bettenauslastung    81
logiernaechte       81
zimmer               0
zimmerauslastung    81
zimmernaechte       81
dtype: int64
indikator   bfs_nr     jahr    monat   betten  bettenauslastung  \
count      29459.0  29459.0  29459.0  29459.0           29378.0
mean        3244.7   2019.4      6.4   1007.2              36.9
std         2076.2      3.9      3.4   1832.3              17.7
min           62.0   2013.0      1.0      4.0               0.0
25%         1202.0   2016.0      3.0    235.0              24.0
50%         3298.0   2019.0      6.0    445.0              35.0
75%         5236.0   2023.0      9.0    859.0              48.0
max         6831.0   2026.0     12.0  19553.0             168.0

indikator  logiernaechte   zimmer  zimmerauslastung  zimmernaechte
count            29378.0  29459.0           29378.0        29378.0
mean             13574.2    519.2              45.7         8475.7
std              30847.8    989.8              19.2        19896.1
min                  1.0      2.0               0.0            1.0
25%               1837.0    116.0              31.0         1226.0
50%               4145.0    223.0              46.0         2727.0
75%              10989.2    445.0              60.0         6790.8
max             424162.0   9795.0              99.0       251419.0
[np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

## 3. Gäste-Herkunft (Tabelle 101)

In [10]:
meta101 = json.loads((RAW / "meta_101.json").read_text(encoding="utf-8"))
gemeinden101 = next(v for v in meta101["variables"] if v["code"] == "Gemeinde")["values"]

def fetch_101(jahr):
    query = {
        "query": [
            {"code": "Jahr",          "selection": {"filter": "item", "values": [str(jahr)]}},
            {"code": "Monat",         "selection": {"filter": "item", "values": [str(m) for m in range(1, 13)]}},
            {"code": "Gemeinde",      "selection": {"filter": "item", "values": gemeinden101}},
            {"code": "Herkunftsland", "selection": {"filter": "item", "values": ["0", "1"]}},
            {"code": "Indikator",     "selection": {"filter": "item", "values": ["2"]}},
        ],
        "response": {"format": "json"},
    }
    r = requests.post(BASE.format(t="101"), json=query, timeout=60)
    r.raise_for_status()
    return r.json()

for jahr in range(2013, 2027):
    ziel = RAW / f"hesta_101_{jahr}.json"
    if ziel.exists():
        continue
    data = fetch_101(jahr)
    ziel.write_text(json.dumps(data), encoding="utf-8")
    print(jahr, len(data["data"]), "Zeilen")
    time.sleep(2)

2013 4464 Zeilen
2014 4464 Zeilen
2015 4464 Zeilen
2016 4464 Zeilen
2017 4464 Zeilen
2018 4464 Zeilen
2019 4464 Zeilen
2020 4464 Zeilen
2021 4464 Zeilen
2022 4464 Zeilen
2023 4464 Zeilen
2024 4464 Zeilen
2025 4464 Zeilen
2026 4464 Zeilen

In [11]:
rows = []
for f in sorted(RAW.glob("hesta_101_*.json")):
    for d in json.loads(f.read_text(encoding="utf-8"))["data"]:
        rows.append(d["key"] + d["values"])     # [Jahr, Monat, Gemeinde, Herkunft, Indikator, Wert]
df101 = pd.DataFrame(rows, columns=["jahr", "monat", "bfs_nr", "herkunft", "indikator", "wert"])
df101["wert"] = pd.to_numeric(df101["wert"], errors="coerce")

herkunft = (df101.pivot_table(index=["bfs_nr", "jahr", "monat"], columns="herkunft",
                              values="wert", aggfunc="first")
            .rename(columns={"0": "ln_total", "1": "ln_schweiz"})
            .reset_index())
herkunft.columns.name = None
herkunft[["bfs_nr", "jahr", "monat"]] = herkunft[["bfs_nr", "jahr", "monat"]].astype(int)

herkunft["ln_ausland"] = herkunft["ln_total"] - herkunft["ln_schweiz"]
herkunft["anteil_ausland"] = (herkunft["ln_ausland"] / herkunft["ln_total"]).where(herkunft["ln_total"] > 0)

herkunft = herkunft[["bfs_nr", "jahr", "monat", "ln_total", "ln_schweiz", "ln_ausland", "anteil_ausland"]]
herkunft.to_csv("../data/processed/herkunft_monat.csv", index=False)
print(herkunft.shape); herkunft.head()

(29378, 7)

   bfs_nr  jahr  monat  ln_total  ln_schweiz  ln_ausland  anteil_ausland
0    1024  2013      1    1737.0       987.0       750.0        0.431779
1    1024  2013     10    2760.0      1381.0      1379.0        0.499638
2    1024  2013     11    2186.0       952.0      1234.0        0.564501
3    1024  2013     12    1882.0       930.0       952.0        0.505845
4    1024  2013      2    1684.0       767.0       917.0        0.544537

In [12]:
print(herkunft.shape)
print(herkunft.isna().sum())
print(herkunft.describe().round(2))
print("negatives ln_ausland:", (herkunft["ln_ausland"] < 0).sum())

chk = hotel.merge(herkunft, on=["bfs_nr", "jahr", "monat"], how="inner")
diff = (chk["logiernaechte"] - chk["ln_total"]).abs()
print("verglichene Zeilen:", len(chk), "| Abweichungen > 0:", (diff > 0).sum())

(29378, 7)
bfs_nr            0
jahr              0
monat             0
ln_total          0
ln_schweiz        0
ln_ausland        0
anteil_ausland    0
dtype: int64
         bfs_nr      jahr     monat   ln_total  ln_schweiz  ln_ausland  \
count  29378.00  29378.00  29378.00   29378.00    29378.00    29378.00
mean    3244.10   2019.43      6.40   13574.23     6293.98     7280.25
std     2075.75      3.95      3.43   30848.03    10580.96    22145.34
min       62.00   2013.00      1.00       1.00        0.00        0.00
25%     1202.00   2016.00      3.00    1837.00     1162.00      477.00
50%     3298.00   2019.00      6.00    4145.00     2464.00     1388.00
75%     5210.00   2023.00      9.00   10989.25     6436.00     4389.50
max     6831.00   2026.00     12.00  424162.00   124342.00   305266.00

       anteil_ausland
count        29378.00
mean             0.38
std              0.20
min              0.00
25%              0.22
50%              0.38
75%              0.53
max              1.00
negatives ln_ausland: 0
verglichene Zeilen: 29378 | Abweichungen > 0: 3

## 4. Gemeinde-Stammdaten (Koordinaten, Höhe)

In [13]:
   import requests, time, json, pathlib
   import pandas as pd

   meta = json.loads((RAW / "meta_201.json").read_text(encoding="utf-8"))
   g = next(v for v in meta["variables"] if v["code"] == "Gemeinde")
   gem = pd.DataFrame({"bfs_nr": g["values"], "name": g["valueTexts"]})
   gem["bfs_nr"] = gem["bfs_nr"].astype(int)
   gem["suchname"] = gem["name"].str.replace(r"\s*\(.*\)", "", regex=True)     # "Brienz (BE)" -> "Brienz"
   gem["kt_hint"] = gem["name"].str.extract(r"\((\w\w)\)")                       # "BE"
   print(gem["kt_hint"].notna().sum(), "Gemeinden mit Kantonshinweis")
   gem.head(10)

8 Gemeinden mit Kantonshinweis

   bfs_nr        name    suchname kt_hint
0      62      Kloten      Kloten     NaN
1      66     Opfikon     Opfikon     NaN
2     191   Dübendorf   Dübendorf     NaN
3     198       Uster       Uster     NaN
4     230  Winterthur  Winterthur     NaN
5     261      Zürich      Zürich     NaN
6     293   Wädenswil   Wädenswil     NaN
7     295      Horgen      Horgen     NaN
8     329  Langenthal  Langenthal     NaN
9     351        Bern        Bern     NaN

In [14]:
   KT = {"ZH": ["zürich", "zurich"], "BE": ["bern"], "LU": ["luzern", "lucerne"], "UR": ["uri"],
         "SZ": ["schwyz"], "OW": ["obwalden"], "NW": ["nidwalden"], "GL": ["glarus"], "ZG": ["zug"],
         "FR": ["freiburg", "fribourg"], "SO": ["solothurn"], "BS": ["basel-stadt"],
         "BL": ["basel-landschaft"], "SH": ["schaffhausen"], "AR": ["ausserrhoden"],
         "AI": ["innerrhoden"], "SG": ["st. gallen", "saint gall"], "GR": ["graubünden", "grisons", "grigioni"],
         "AG": ["aargau"], "TG": ["thurgau"], "TI": ["tessin", "ticino"], "VD": ["waadt", "vaud"],
         "VS": ["wallis", "valais"], "NE": ["neuenburg", "neuchâtel", "neuchatel"],
         "GE": ["genf", "genève", "geneva"], "JU": ["jura"]}

   def geocode(name):
       r = requests.get("https://geocoding-api.open-meteo.com/v1/search",
                        params={"name": name, "count": 10, "language": "de",
                                "countryCode": "CH", "format": "json"}, timeout=30)
       r.raise_for_status()
       return r.json().get("results", [])

   def waehle(res, kt):
       if not res:
           return None, False
       if isinstance(kt, str) and kt in KT:
           for r in res:
               if any(k in r.get("admin1", "").lower() for k in KT[kt]):
                   return r, True
           return res[0], False            # kein Treffer im richtigen Kanton
       return res[0], True

   treffer = []
   for row in gem.itertuples():
       res = geocode(row.suchname)
       best, kt_ok = waehle(res, row.kt_hint)
       best = best or {}
       treffer.append({"bfs_nr": row.bfs_nr, "lat": best.get("latitude"), "lon": best.get("longitude"),
                       "hoehe_m": best.get("elevation"), "ort_gefunden": best.get("name"),
                       "kanton_geo": best.get("admin1"), "n_treffer": len(res), "kt_ok": kt_ok})
       time.sleep(0.5)

   gem = gem.merge(pd.DataFrame(treffer), on="bfs_nr")
   gem.to_csv("../data/processed/gemeinden_roh.csv", index=False)
   print("ohne Treffer:", gem["lat"].isna().sum())
   print("Kanton passt nicht:", (~gem["kt_ok"] & gem["lat"].notna()).sum())
   print("mehrere Treffer:", (gem["n_treffer"] > 1).sum())

ohne Treffer: 23
Kanton passt nicht: 1
mehrere Treffer: 66

In [ ]:
   print(gem.sort_values("hoehe_m")[["bfs_nr", "name", "ort_gefunden", "kanton_geo", "hoehe_m", "n_treffer", "kt_ok"]]
         .to_string(index=False))

## 4. Gemeinde-Stammdaten (Koordinaten, Höhe)

In [2]:
import requests, time, json, pathlib
import pandas as pd

RAW = pathlib.Path("../data/raw/bfs")

meta = json.loads((RAW / "meta_201.json").read_text(encoding="utf-8"))
g = next(v for v in meta["variables"] if v["code"] == "Gemeinde")
gem = pd.DataFrame({"bfs_nr": g["values"], "name": g["valueTexts"]})
gem["bfs_nr"] = gem["bfs_nr"].astype(int)
gem["suchname"] = gem["name"].str.replace(r"\s*\(.*\)", "", regex=True)     # "Brienz (BE)" -> "Brienz"
gem["kt_hint"] = gem["name"].str.extract(r"\((\w\w)\)")                       # "BE"
print(gem["kt_hint"].notna().sum(), "Gemeinden mit Kantonshinweis")
gem.head(10)

8 Gemeinden mit Kantonshinweis

   bfs_nr        name    suchname kt_hint
0      62      Kloten      Kloten     NaN
1      66     Opfikon     Opfikon     NaN
2     191   Dübendorf   Dübendorf     NaN
3     198       Uster       Uster     NaN
4     230  Winterthur  Winterthur     NaN
5     261      Zürich      Zürich     NaN
6     293   Wädenswil   Wädenswil     NaN
7     295      Horgen      Horgen     NaN
8     329  Langenthal  Langenthal     NaN
9     351        Bern        Bern     NaN

In [3]:
   KT = {"ZH": ["zürich", "zurich"], "BE": ["bern"], "LU": ["luzern", "lucerne"], "UR": ["uri"],
         "SZ": ["schwyz"], "OW": ["obwalden"], "NW": ["nidwalden"], "GL": ["glarus"], "ZG": ["zug"],
         "FR": ["freiburg", "fribourg"], "SO": ["solothurn"], "BS": ["basel-stadt"],
         "BL": ["basel-landschaft"], "SH": ["schaffhausen"], "AR": ["ausserrhoden"],
         "AI": ["innerrhoden"], "SG": ["st. gallen", "saint gall"], "GR": ["graubünden", "grisons", "grigioni"],
         "AG": ["aargau"], "TG": ["thurgau"], "TI": ["tessin", "ticino"], "VD": ["waadt", "vaud"],
         "VS": ["wallis", "valais"], "NE": ["neuenburg", "neuchâtel", "neuchatel"],
         "GE": ["genf", "genève", "geneva"], "JU": ["jura"]}

   def geocode(name):
       r = requests.get("https://geocoding-api.open-meteo.com/v1/search",
                        params={"name": name, "count": 10, "language": "de",
                                "countryCode": "CH", "format": "json"}, timeout=30)
       r.raise_for_status()
       return r.json().get("results", [])

   def waehle(res, kt):
       if not res:
           return None, False
       if isinstance(kt, str) and kt in KT:
           for r in res:
               if any(k in r.get("admin1", "").lower() for k in KT[kt]):
                   return r, True
           return res[0], False            # kein Treffer im richtigen Kanton
       return res[0], True

   treffer = []
   for row in gem.itertuples():
       res = geocode(row.suchname)
       best, kt_ok = waehle(res, row.kt_hint)
       best = best or {}
       treffer.append({"bfs_nr": row.bfs_nr, "lat": best.get("latitude"), "lon": best.get("longitude"),
                       "hoehe_m": best.get("elevation"), "ort_gefunden": best.get("name"),
                       "kanton_geo": best.get("admin1"), "n_treffer": len(res), "kt_ok": kt_ok})
       time.sleep(0.5)

   gem = gem.merge(pd.DataFrame(treffer), on="bfs_nr")
   gem.to_csv("../data/processed/gemeinden_roh.csv", index=False)
   print("ohne Treffer:", gem["lat"].isna().sum())
   print("Kanton passt nicht:", (~gem["kt_ok"] & gem["lat"].notna()).sum())
   print("mehrere Treffer:", (gem["n_treffer"] > 1).sum())

ohne Treffer: 23
Kanton passt nicht: 1
mehrere Treffer: 66

In [4]:
   print(gem.sort_values("hoehe_m")[["bfs_nr", "name", "ort_gefunden", "kanton_geo", "hoehe_m", "n_treffer", "kt_ok"]]
         .to_string(index=False))

 bfs_nr                     name             ort_gefunden                    kanton_geo  hoehe_m  n_treffer  kt_ok
   5091                   Ascona                   Ascona                 Kanton Tessin    202.0          1   True
   5113                  Locarno                  Locarno                 Kanton Tessin    206.0          2   True
   5120                  Muralto                  Muralto                 Kanton Tessin    221.0          1   True
   5002               Bellinzona               Bellinzona                 Kanton Tessin    230.0          1   True
   5250                  Chiasso                  Chiasso                 Kanton Tessin    237.0          1   True
   4258              Rheinfelden      Rheinfelden, Aargau                 Kanton Aargau    277.0          1   True
   2701                    Basel                    Basel            Kanton Basel-Stadt    279.0          2   True
   5192                   Lugano                   Lugano                 Kanton Tessin    284.0          3   True
   2831                 Pratteln                 Pratteln       Kanton Basel-Landschaft    291.0          1   True
   5210                 Paradiso              Paradiso TI                 Kanton Tessin    296.0          1   True
   2829                  Liestal                  Liestal       Kanton Basel-Landschaft    327.0          1   True
   5254                Mendrisio                Mendrisio                 Kanton Tessin    338.0          1   True
   5642                   Morges                   Morges                  Kanton Waadt    380.0          2   True
   4021                    Baden                 Baden AG                 Kanton Aargau    381.0          2   True
   5890                    Vevey                    Vevey                  Kanton Waadt    388.0          1   True
   4001                    Aarau                    Aarau                 Kanton Aargau    389.0          1   True
   6621                   Genève                     Genf                   Kanton Genf    400.0          1   True
   5724                     Nyon                     Nyon                  Kanton Waadt    401.0          1   True
   4201                 Lenzburg                 Lenzburg                 Kanton Aargau    402.0          1   True
   2939             Schaffhausen             Schaffhausen           Kanton Schaffhausen    403.0          3   True
   5886                 Montreux                 Montreux                  Kanton Waadt    403.0          1   True
   2581                    Olten                    Olten              Kanton Solothurn    406.0          1   True
   4401                    Arbon                    Arbon                Kanton Thurgau    408.0          1   True
   1322               Freienbach               Freienbach                 Kanton Schwyz    410.0          1   True
   4671              Kreuzlingen              Kreuzlingen                Kanton Thurgau    414.0          1   True
    295                   Horgen                   Horgen                 Kanton Zürich    415.0          8   True
   4566               Frauenfeld               Frauenfeld                Kanton Thurgau    417.0          1   True
   6217            Saint-Maurice         Saint-Maurice VS                 Kanton Wallis    419.0          1   True
   6628                    Lancy                    Lancy                   Kanton Genf    421.0          1   True
   6800               Porrentruy               Porrentruy                   Kanton Jura    425.0          2   True
   1711                      Zug                      Zug                    Kanton Zug    425.0          4   True
   3298               Walenstadt               Walenstadt             Kanton St. Gallen    426.0          2   True
    261                   Zürich                   Zürich                 Kanton Zürich    429.0         10   True
   6711                 Delémont                 Delémont                   Kanton Jura    432.0          1   True
   2401               Egerkingen               Egerkingen              Kanton Solothurn    433.0          1   True
   1501               Beckenried               Beckenried              Kanton Nidwalden    434.0          1   True
    371              Biel/Bienne                     Biel                   Kanton Bern    434.0          1   True
   2275                   Murten                   Murten               Kanton Freiburg    435.0          1   True
    191                Dübendorf                Dübendorf                 Kanton Zürich    436.0         10   True
   1061                   Luzern                   Luzern                 Kanton Luzern    437.0          3   True
   5938        Yverdon-les-Bains        Yverdon-les-Bains                  Kanton Waadt    438.0          1   True
     66                  Opfikon                  Opfikon                 Kanton Zürich    438.0          1   True
   1364                Ingenbohl                Ingenbohl                 Kanton Schwyz    438.0          1   True
     62                   Kloten                   Kloten                 Kanton Zürich    439.0         10   True
   1069                   Weggis                   Weggis                 Kanton Luzern    439.0          1   True
   2601                Solothurn                Solothurn              Kanton Solothurn    440.0          5   True
   6643                  Vernier                  Vernier                   Kanton Genf    440.0          1   True
   1331           Küssnacht (SZ)             Küssnacht SZ                 Kanton Schwyz    440.0          1   True
   6458                Neuchâtel                Neuenburg              Kanton Neuenburg    441.0          2   True
   4289                 Zofingen                 Zofingen                 Kanton Aargau    441.0          1   True
    230               Winterthur               Winterthur                 Kanton Zürich    441.0          3   True
   6630                   Meyrin                   Meyrin                   Kanton Genf    445.0          1   True
   3251               Altstätten            Altstätten SG             Kanton St. Gallen    447.0          1   True
   3271               Buchs (SG)                 Buchs SG             Kanton St. Gallen    447.0         10   True
   1068                  Vitznau                  Vitznau                 Kanton Luzern    448.0          1   True
    293                Wädenswil                Wädenswil                 Kanton Zürich    450.0          8   True
   5409                    Ollon                    Ollon                  Kanton Waadt    452.0          2   True
   5586                 Lausanne                 Lausanne                  Kanton Waadt    453.0          2   True
   3216          Rorschacherberg          Rorschacherberg             Kanton St. Gallen    453.0          1   True
   2546                 Grenchen                 Grenchen              Kanton Solothurn    454.0          6   True
   3292                    Flums                    Flums             Kanton St. Gallen    456.0          9   True
    783                Hasliberg                Hasliberg                 Kanton Zürich    464.0          7   True
   1024                    Emmen                    Emmen                 Kanton Luzern    464.0          5   True
    198                    Uster                    Uster                 Kanton Zürich    469.0          7   True
   1407                   Sarnen                   Sarnen               Kanton Obwalden    473.0          1   True
    979          Herzogenbuchsee          Herzogenbuchsee                   Kanton Bern    474.0          1   True
   6136                 Martigny           Martigny-Ville                 Kanton Wallis    475.0          4   True
   1059                   Kriens                   Kriens                 Kanton Luzern    476.0          1   True
   1063                   Meggen                   Meggen                 Kanton Luzern    476.0          2   True
   1406                 Sachseln                 Sachseln               Kanton Obwalden    477.0          1   True
    329               Langenthal               Langenthal                   Kanton Bern    478.0          2   True
   3342          Eschenbach (SG)            Eschenbach SG             Kanton St. Gallen    480.0          2   True
   6266                     Sion         Flughafen Sitten                 Kanton Wallis    483.0          1   True
   1103                   Sursee                   Sursee                 Kanton Luzern    503.0          1   True
   3953                Maienfeld             Maienfeld GR             Kanton Graubünden    506.0          2   True
   3291                Bad Ragaz                Bad Ragaz             Kanton St. Gallen    512.0          1   True
   1372                   Schwyz                   Schwyz                 Kanton Schwyz    521.0          1   True
   6248                   Sierre                   Siders                 Kanton Wallis    528.0          1   True
   6831             Moutier (JU)                  Moutier                   Kanton Jura    535.0          1   True
    404                 Burgdorf                 Burgdorf                   Kanton Bern    535.0          1   True
    700             Moutier (BE)                  Moutier                   Kanton Jura    535.0          1  False
   3408                    Uzwil                    Uzwil             Kanton St. Gallen    542.0          1   True
    351                     Bern                     Bern                   Kanton Bern    549.0         10   True
    942                     Thun                     Thun                   Kanton Bern    560.0          6   True
    573              Brienz (BE)                   Brienz                   Kanton Bern    563.0          4   True
   3427                 Wil (SG)                   Wil SG             Kanton St. Gallen    569.0         10   True
    593                Unterseen                Unterseen                   Kanton Bern    570.0          1   True
    581               Interlaken               Interlaken                   Kanton Bern    570.0          2   True
   3295                  Quarten                  Quarten             Kanton St. Gallen    574.0          1   True
    587    Matten bei Interlaken    Matten bei Interlaken                   Kanton Bern    576.0          1   True
    355                    Köniz                    Köniz                   Kanton Bern    577.0          2   True
    768                    Spiez                    Spiez                   Kanton Bern    595.0          1   True
    594               Wilderswil               Wilderswil                   Kanton Bern    598.0          1   True
    785                Meiringen                Meiringen                   Kanton Bern    599.0          2   True
   3901                     Chur                     Chur             Kanton Graubünden    601.0          6   True
   2196                 Fribourg                 Freiburg               Kanton Freiburg    610.0          1   True
    784            Innertkirchen            Innertkirchen                   Kanton Bern    627.0          1   True
   1366                Morschach                Morschach                 Kanton Schwyz    648.0          1   True
   6297                     Visp                     Visp                 Kanton Wallis    653.0          2   True
    902      Langnau im Emmental      Langnau im Emmental                   Kanton Bern    677.0          1   True
   3203               St. Gallen               St. Gallen             Kanton St. Gallen    684.0          3   True
   1321               Feusisberg               Feusisberg                 Kanton Schwyz    696.0          1   True
   6808            Clos du Doubs            Clos du Doubs                   Kanton Bern    702.0          1   True
    567 Reichenbach im Kandertal Reichenbach im Kandertal                   Kanton Bern    712.0          1   True
   1709               Unterägeri               Unterägeri                    Kanton Zug    727.0          1   True
   1504                 Emmetten                 Emmetten              Kanton Nidwalden    761.0          1   True
   2125                    Bulle                    Bulle               Kanton Freiburg    771.0          2   True
   3101                Appenzell                Appenzell  Kanton Appenzell Innerrhoden    783.0          6   True
   3032                   Heiden                Heiden AR Kanton Appenzell Ausserrhoden    786.0          6   True
    584            Lauterbrunnen            Lauterbrunnen                   Kanton Bern    787.0          3   True
   3002                  Hundwil                  Hundwil Kanton Appenzell Ausserrhoden    792.0          2   True
    938                Sigriswil                Sigriswil                   Kanton Bern    797.0          2   True
   2135                 Gruyères                 Gruyères               Kanton Freiburg    805.0          2   True
    762                Diemtigen                Diemtigen                   Kanton Bern    814.0          1   True
   3024              Teufen (AR)                Teufen AR Kanton Appenzell Ausserrhoden    842.0          5   True
   2299                Plaffeien                Plaffeien               Kanton Freiburg    854.0          1   True
    562         Aeschi bei Spiez         Aeschi bei Spiez                   Kanton Bern    860.0          1   True
   1301               Einsiedeln               Einsiedeln                 Kanton Schwyz    882.0          1   True
   6034                 Orsières                 Orsières                 Kanton Wallis    897.0          1   True
   3102                   Gonten                   Gonten  Kanton Appenzell Innerrhoden    900.0          4   True
   3311                    Amden                    Amden             Kanton St. Gallen    903.0          1   True
   3022                     Gais                  Gais AR Kanton Appenzell Ausserrhoden    924.0          3   True
    906                Schangnau                Schangnau                   Kanton Bern    930.0          1   True
   1209               Gurtnellen               Gurtnellen                    Kanton Uri    932.0          1   True
   5841            Château-d'Oex            Château-d'Oex                  Kanton Waadt    962.0          1   True
   6757             Saignelégier             Saignelégier                   Kanton Jura    985.0          1   True
   6421        La Chaux-de-Fonds        La Chaux-de-Fonds              Kanton Neuenburg    995.0          1   True
   6024                   Nendaz             Basse-Nendaz                 Kanton Wallis   1004.0          1   True
   3561                Poschiavo                Poschiavo             Kanton Graubünden   1010.0          1   True
    843                   Saanen                   Saanen                   Kanton Bern   1010.0          4   True
   3575                     Laax                     Laax             Kanton Graubünden   1011.0          2   True
   5872                Le Chenit                Le Chenit                  Kanton Waadt   1015.0          1   True
   1402                Engelberg                Engelberg               Kanton Obwalden   1015.0          5   True
    576              Grindelwald              Grindelwald                   Kanton Bern   1047.0          1   True
   6151                 Champéry                 Champéry                 Kanton Wallis   1048.0          1   True
    792                     Lenk        Lenk im Simmental                   Kanton Bern   1067.0          2   True
   3732                    Flims                    Flims             Kanton Graubünden   1085.0          4   True
   5552                   Bullet                Bullet VD                  Kanton Waadt   1146.0          1   True
    571               Beatenberg               Beatenberg                   Kanton Bern   1172.0          2   True
    565               Kandersteg               Kandersteg                   Kanton Bern   1172.0          1   True
   3871                 Klosters                 Klosters             Kanton Graubünden   1200.0          3   True
   3762                    Scuol                    Scuol             Kanton Graubünden   1250.0          1   True
   3603                     Vals                     Vals             Kanton Graubünden   1252.0          6   True
   5407                   Leysin                   Leysin                  Kanton Waadt   1262.0          2   True
   3981            Breil/Brigels                  Brigels             Kanton Graubünden   1281.0          1   True
    561                Adelboden                Adelboden                   Kanton Bern   1328.0          2   True
   6083                  Evolène                  Evolène                 Kanton Wallis   1340.0          1   True
   3506              Vaz/Obervaz                  Obervaz             Kanton Graubünden   1355.0          1   True
   6111                Leukerbad                Leukerbad                 Kanton Wallis   1383.0          1   True
   1202                Andermatt                Andermatt                    Kanton Uri   1441.0          1   True
   3746                   Zernez                   Zernez             Kanton Graubünden   1477.0          1   True
   6253            Crans-Montana            Crans-Montana                 Kanton Wallis   1547.0          1   True
   3851                    Davos                    Davos             Kanton Graubünden   1560.0         10   True
   6291               Saas-Grund               Saas-Grund                 Kanton Wallis   1564.0          1   True
   6300                  Zermatt                  Zermatt                 Kanton Wallis   1608.0          2   True
   3786                  Samedan                  Samedan             Kanton Graubünden   1716.0          2   True
   3782      Celerina/Schlarigna                 Celerina             Kanton Graubünden   1727.0          1   True
   3921                    Arosa                    Arosa             Kanton Graubünden   1775.0          1   True
   6290                 Saas-Fee                 Saas-Fee                 Kanton Wallis   1800.0          1   True
   3784               Pontresina               Pontresina             Kanton Graubünden   1822.0          1   True
   3752                  Samnaun                  Samnaun             Kanton Graubünden   1841.0          2   True
   3787               St. Moritz             Sankt Moritz             Kanton Graubünden   1845.0          3   True
   3714                Rheinwald            Rheinwaldhorn             Kanton Graubünden   3402.0          1   True
   1630              Glarus Nord                      NaN                           NaN      NaN          0  False
   1631               Glarus Süd                      NaN                           NaN      NaN          0  False
   2121            Haut-Intyamon                      NaN                           NaN      NaN          0  False
   3340          Rapperswil-Jona                      NaN                           NaN      NaN          0  False
   3359  Wildhaus-Alt St. Johann                      NaN                           NaN      NaN          0  False
   3396                Neckertal                      NaN                           NaN      NaN          0  False
   3543                   Surses                      NaN                           NaN      NaN          0  False
   3618                 Lumnezia                      NaN                           NaN      NaN          0  False
   3619              Ilanz/Glion                      NaN                           NaN      NaN          0  False

In [6]:
print("--- OHNE TREFFER ---")
print("\n".join(f"{r.bfs_nr}|{r.name}" for r in gem[gem["lat"].isna()].itertuples()))
print("--- ALLE (nach Höhe) ---")
print("\n".join(f"{r.bfs_nr}|{r.name}|{r.ort_gefunden}|{r.kanton_geo}|{r.hoehe_m}|{r.n_treffer}|{int(r.kt_ok)}"
                for r in gem.dropna(subset=["lat"]).sort_values("hoehe_m").itertuples()))

--- OHNE TREFFER ---
1630|Glarus Nord
1631|Glarus Süd
2121|Haut-Intyamon
3340|Rapperswil-Jona
3359|Wildhaus-Alt St. Johann
3396|Neckertal
3543|Surses
3618|Lumnezia
3619|Ilanz/Glion
3792|Bregaglia
3847|Val Müstair
3986|Tujetsch
5236|Collina d'Oro
5238|Monteceneri
5411|Ormont-Dessus
5613|Bourg-en-Lavaux
5892|Blonay - Saint-Légier
6002|Brig-Glis
6037|Val de Bagnes
6077|Goms
6252|Anniviers
6417|La Grande Béroche
6513|Laténa
--- ALLE (nach Höhe) ---
5091|Ascona|Ascona|Kanton Tessin|202.0|1|1
5113|Locarno|Locarno|Kanton Tessin|206.0|2|1
5120|Muralto|Muralto|Kanton Tessin|221.0|1|1
5002|Bellinzona|Bellinzona|Kanton Tessin|230.0|1|1
5250|Chiasso|Chiasso|Kanton Tessin|237.0|1|1
4258|Rheinfelden|Rheinfelden, Aargau|Kanton Aargau|277.0|1|1
2701|Basel|Basel|Kanton Basel-Stadt|279.0|2|1
5192|Lugano|Lugano|Kanton Tessin|284.0|3|1
2831|Pratteln|Pratteln|Kanton Basel-Landschaft|291.0|1|1
5210|Paradiso|Paradiso TI|Kanton Tessin|296.0|1|1
2829|Liestal|Liestal|Kanton Basel-Landschaft|327.0|1|1
5254|Mendrisio|Mendrisio|Kanton Tessin|338.0|1|1
5642|Morges|Morges|Kanton Waadt|380.0|2|1
4021|Baden|Baden AG|Kanton Aargau|381.0|2|1
5890|Vevey|Vevey|Kanton Waadt|388.0|1|1
4001|Aarau|Aarau|Kanton Aargau|389.0|1|1
6621|Genève|Genf|Kanton Genf|400.0|1|1
5724|Nyon|Nyon|Kanton Waadt|401.0|1|1
4201|Lenzburg|Lenzburg|Kanton Aargau|402.0|1|1
2939|Schaffhausen|Schaffhausen|Kanton Schaffhausen|403.0|3|1
5886|Montreux|Montreux|Kanton Waadt|403.0|1|1
2581|Olten|Olten|Kanton Solothurn|406.0|1|1
4401|Arbon|Arbon|Kanton Thurgau|408.0|1|1
1322|Freienbach|Freienbach|Kanton Schwyz|410.0|1|1
4671|Kreuzlingen|Kreuzlingen|Kanton Thurgau|414.0|1|1
295|Horgen|Horgen|Kanton Zürich|415.0|8|1
4566|Frauenfeld|Frauenfeld|Kanton Thurgau|417.0|1|1
6217|Saint-Maurice|Saint-Maurice VS|Kanton Wallis|419.0|1|1
6628|Lancy|Lancy|Kanton Genf|421.0|1|1
6800|Porrentruy|Porrentruy|Kanton Jura|425.0|2|1
1711|Zug|Zug|Kanton Zug|425.0|4|1
3298|Walenstadt|Walenstadt|Kanton St. Gallen|426.0|2|1
261|Zürich|Zürich|Kanton Zürich|429.0|10|1
6711|Delémont|Delémont|Kanton Jura|432.0|1|1
2401|Egerkingen|Egerkingen|Kanton Solothurn|433.0|1|1
1501|Beckenried|Beckenried|Kanton Nidwalden|434.0|1|1
371|Biel/Bienne|Biel|Kanton Bern|434.0|1|1
2275|Murten|Murten|Kanton Freiburg|435.0|1|1
191|Dübendorf|Dübendorf|Kanton Zürich|436.0|10|1
1061|Luzern|Luzern|Kanton Luzern|437.0|3|1
5938|Yverdon-les-Bains|Yverdon-les-Bains|Kanton Waadt|438.0|1|1
66|Opfikon|Opfikon|Kanton Zürich|438.0|1|1
1364|Ingenbohl|Ingenbohl|Kanton Schwyz|438.0|1|1
62|Kloten|Kloten|Kanton Zürich|439.0|10|1
1069|Weggis|Weggis|Kanton Luzern|439.0|1|1
2601|Solothurn|Solothurn|Kanton Solothurn|440.0|5|1
6643|Vernier|Vernier|Kanton Genf|440.0|1|1
1331|Küssnacht (SZ)|Küssnacht SZ|Kanton Schwyz|440.0|1|1
6458|Neuchâtel|Neuenburg|Kanton Neuenburg|441.0|2|1
4289|Zofingen|Zofingen|Kanton Aargau|441.0|1|1
230|Winterthur|Winterthur|Kanton Zürich|441.0|3|1
6630|Meyrin|Meyrin|Kanton Genf|445.0|1|1
3251|Altstätten|Altstätten SG|Kanton St. Gallen|447.0|1|1
3271|Buchs (SG)|Buchs SG|Kanton St. Gallen|447.0|10|1
1068|Vitznau|Vitznau|Kanton Luzern|448.0|1|1
293|Wädenswil|Wädenswil|Kanton Zürich|450.0|8|1
5409|Ollon|Ollon|Kanton Waadt|452.0|2|1
5586|Lausanne|Lausanne|Kanton Waadt|453.0|2|1
3216|Rorschacherberg|Rorschacherberg|Kanton St. Gallen|453.0|1|1
2546|Grenchen|Grenchen|Kanton Solothurn|454.0|6|1
3292|Flums|Flums|Kanton St. Gallen|456.0|9|1
783|Hasliberg|Hasliberg|Kanton Zürich|464.0|7|1
1024|Emmen|Emmen|Kanton Luzern|464.0|5|1
198|Uster|Uster|Kanton Zürich|469.0|7|1
1407|Sarnen|Sarnen|Kanton Obwalden|473.0|1|1
979|Herzogenbuchsee|Herzogenbuchsee|Kanton Bern|474.0|1|1
6136|Martigny|Martigny-Ville|Kanton Wallis|475.0|4|1
1059|Kriens|Kriens|Kanton Luzern|476.0|1|1
1063|Meggen|Meggen|Kanton Luzern|476.0|2|1
1406|Sachseln|Sachseln|Kanton Obwalden|477.0|1|1
329|Langenthal|Langenthal|Kanton Bern|478.0|2|1
3342|Eschenbach (SG)|Eschenbach SG|Kanton St. Gallen|480.0|2|1
6266|Sion|Flughafen Sitten|Kanton Wallis|483.0|1|1
1103|Sursee|Sursee|Kanton Luzern|503.0|1|1
3953|Maienfeld|Maienfeld GR|Kanton Graubünden|506.0|2|1
3291|Bad Ragaz|Bad Ragaz|Kanton St. Gallen|512.0|1|1
1372|Schwyz|Schwyz|Kanton Schwyz|521.0|1|1
6248|Sierre|Siders|Kanton Wallis|528.0|1|1
6831|Moutier (JU)|Moutier|Kanton Jura|535.0|1|1
404|Burgdorf|Burgdorf|Kanton Bern|535.0|1|1
700|Moutier (BE)|Moutier|Kanton Jura|535.0|1|0
3408|Uzwil|Uzwil|Kanton St. Gallen|542.0|1|1
351|Bern|Bern|Kanton Bern|549.0|10|1
942|Thun|Thun|Kanton Bern|560.0|6|1
573|Brienz (BE)|Brienz|Kanton Bern|563.0|4|1
3427|Wil (SG)|Wil SG|Kanton St. Gallen|569.0|10|1
593|Unterseen|Unterseen|Kanton Bern|570.0|1|1
581|Interlaken|Interlaken|Kanton Bern|570.0|2|1
3295|Quarten|Quarten|Kanton St. Gallen|574.0|1|1
587|Matten bei Interlaken|Matten bei Interlaken|Kanton Bern|576.0|1|1
355|Köniz|Köniz|Kanton Bern|577.0|2|1
768|Spiez|Spiez|Kanton Bern|595.0|1|1
594|Wilderswil|Wilderswil|Kanton Bern|598.0|1|1
785|Meiringen|Meiringen|Kanton Bern|599.0|2|1
3901|Chur|Chur|Kanton Graubünden|601.0|6|1
2196|Fribourg|Freiburg|Kanton Freiburg|610.0|1|1
784|Innertkirchen|Innertkirchen|Kanton Bern|627.0|1|1
1366|Morschach|Morschach|Kanton Schwyz|648.0|1|1
6297|Visp|Visp|Kanton Wallis|653.0|2|1
902|Langnau im Emmental|Langnau im Emmental|Kanton Bern|677.0|1|1
3203|St. Gallen|St. Gallen|Kanton St. Gallen|684.0|3|1
1321|Feusisberg|Feusisberg|Kanton Schwyz|696.0|1|1
6808|Clos du Doubs|Clos du Doubs|Kanton Bern|702.0|1|1
567|Reichenbach im Kandertal|Reichenbach im Kandertal|Kanton Bern|712.0|1|1
1709|Unterägeri|Unterägeri|Kanton Zug|727.0|1|1
1504|Emmetten|Emmetten|Kanton Nidwalden|761.0|1|1
2125|Bulle|Bulle|Kanton Freiburg|771.0|2|1
3101|Appenzell|Appenzell|Kanton Appenzell Innerrhoden|783.0|6|1
3032|Heiden|Heiden AR|Kanton Appenzell Ausserrhoden|786.0|6|1
584|Lauterbrunnen|Lauterbrunnen|Kanton Bern|787.0|3|1
3002|Hundwil|Hundwil|Kanton Appenzell Ausserrhoden|792.0|2|1
938|Sigriswil|Sigriswil|Kanton Bern|797.0|2|1
2135|Gruyères|Gruyères|Kanton Freiburg|805.0|2|1
762|Diemtigen|Diemtigen|Kanton Bern|814.0|1|1
3024|Teufen (AR)|Teufen AR|Kanton Appenzell Ausserrhoden|842.0|5|1
2299|Plaffeien|Plaffeien|Kanton Freiburg|854.0|1|1
562|Aeschi bei Spiez|Aeschi bei Spiez|Kanton Bern|860.0|1|1
1301|Einsiedeln|Einsiedeln|Kanton Schwyz|882.0|1|1
6034|Orsières|Orsières|Kanton Wallis|897.0|1|1
3102|Gonten|Gonten|Kanton Appenzell Innerrhoden|900.0|4|1
3311|Amden|Amden|Kanton St. Gallen|903.0|1|1
3022|Gais|Gais AR|Kanton Appenzell Ausserrhoden|924.0|3|1
906|Schangnau|Schangnau|Kanton Bern|930.0|1|1
1209|Gurtnellen|Gurtnellen|Kanton Uri|932.0|1|1
5841|Château-d'Oex|Château-d'Oex|Kanton Waadt|962.0|1|1
6757|Saignelégier|Saignelégier|Kanton Jura|985.0|1|1
6421|La Chaux-de-Fonds|La Chaux-de-Fonds|Kanton Neuenburg|995.0|1|1
6024|Nendaz|Basse-Nendaz|Kanton Wallis|1004.0|1|1
3561|Poschiavo|Poschiavo|Kanton Graubünden|1010.0|1|1
843|Saanen|Saanen|Kanton Bern|1010.0|4|1
3575|Laax|Laax|Kanton Graubünden|1011.0|2|1
5872|Le Chenit|Le Chenit|Kanton Waadt|1015.0|1|1
1402|Engelberg|Engelberg|Kanton Obwalden|1015.0|5|1
576|Grindelwald|Grindelwald|Kanton Bern|1047.0|1|1
6151|Champéry|Champéry|Kanton Wallis|1048.0|1|1
792|Lenk|Lenk im Simmental|Kanton Bern|1067.0|2|1
3732|Flims|Flims|Kanton Graubünden|1085.0|4|1
5552|Bullet|Bullet VD|Kanton Waadt|1146.0|1|1
571|Beatenberg|Beatenberg|Kanton Bern|1172.0|2|1
565|Kandersteg|Kandersteg|Kanton Bern|1172.0|1|1
3871|Klosters|Klosters|Kanton Graubünden|1200.0|3|1
3762|Scuol|Scuol|Kanton Graubünden|1250.0|1|1
3603|Vals|Vals|Kanton Graubünden|1252.0|6|1
5407|Leysin|Leysin|Kanton Waadt|1262.0|2|1
3981|Breil/Brigels|Brigels|Kanton Graubünden|1281.0|1|1
561|Adelboden|Adelboden|Kanton Bern|1328.0|2|1
6083|Evolène|Evolène|Kanton Wallis|1340.0|1|1
3506|Vaz/Obervaz|Obervaz|Kanton Graubünden|1355.0|1|1
6111|Leukerbad|Leukerbad|Kanton Wallis|1383.0|1|1
1202|Andermatt|Andermatt|Kanton Uri|1441.0|1|1
3746|Zernez|Zernez|Kanton Graubünden|1477.0|1|1
6253|Crans-Montana|Crans-Montana|Kanton Wallis|1547.0|1|1
3851|Davos|Davos|Kanton Graubünden|1560.0|10|1
6291|Saas-Grund|Saas-Grund|Kanton Wallis|1564.0|1|1
6300|Zermatt|Zermatt|Kanton Wallis|1608.0|2|1
3786|Samedan|Samedan|Kanton Graubünden|1716.0|2|1
3782|Celerina/Schlarigna|Celerina|Kanton Graubünden|1727.0|1|1
3921|Arosa|Arosa|Kanton Graubünden|1775.0|1|1
6290|Saas-Fee|Saas-Fee|Kanton Wallis|1800.0|1|1
3784|Pontresina|Pontresina|Kanton Graubünden|1822.0|1|1
3752|Samnaun|Samnaun|Kanton Graubünden|1841.0|2|1
3787|St. Moritz|Sankt Moritz|Kanton Graubünden|1845.0|3|1
3714|Rheinwald|Rheinwaldhorn|Kanton Graubünden|3402.0|1|1

### Korrektur der Gemeinden ohne oder mit falschem Treffer

In [11]:
korr = pd.read_csv("../data/manual/gemeinde_korrektur.csv", encoding="utf-8")
korr_rows = []
for row in korr.itertuples():
    res = geocode(row.referenzort)
    best, kt_ok = waehle(res, row.kt)
    best = best or {}
    korr_rows.append({"bfs_nr": row.bfs_nr, "lat_k": best.get("latitude"), "lon_k": best.get("longitude"),
                      "hoehe_k": best.get("elevation"), "ort_k": best.get("name"), "kt_ok_k": kt_ok})
    time.sleep(0.5)
korr_geo = pd.DataFrame(korr_rows)
print(korr.merge(korr_geo, on="bfs_nr")[["bfs_nr", "name", "referenzort", "ort_k", "hoehe_k", "kt_ok_k"]].to_string(index=False))

 bfs_nr                    name       referenzort                  ort_k  hoehe_k  kt_ok_k
   1630             Glarus Nord            Näfels                 Näfels    437.0     True
   1631              Glarus Süd               Elm                 Elm GL    977.0     True
   2121           Haut-Intyamon           Albeuve                Albeuve    759.0     True
   3340         Rapperswil-Jona        Rapperswil          Rapperswil SG    408.0     True
   3359 Wildhaus-Alt St. Johann          Wildhaus            Wildhaus SG   1090.0     True
   3396               Neckertal        Brunnadern             Brunnadern    659.0     True
   3543                  Surses          Savognin               Savognin   1219.0     True
   3618                Lumnezia             Villa                  Villa   1253.0     True
   3619             Ilanz/Glion             Ilanz                  Ilanz    705.0     True
   3792               Bregaglia            Soglio              Soglio GR   1099.0     True
   3847             Val Müstair           Müstair                Müstair   1256.0     True
   3986                Tujetsch            Sedrun                 Sedrun   1402.0     True
   5236           Collina d'Oro        Montagnola             Montagnola    473.0     True
   5238             Monteceneri            Rivera              Rivera TI    472.0     True
   5411           Ormont-Dessus    Les Diablerets         Les Diablerets   1181.0     True
   5613         Bourg-en-Lavaux             Cully               Cully VD    392.0     True
   5892   Blonay - Saint-Légier            Blonay                 Blonay    629.0     True
   6002               Brig-Glis              Brig                   Brig    680.0     True
   6037           Val de Bagnes           Verbier                Verbier   1515.0     True
   6077                    Goms           Münster      Münster-Geschinen   1382.0     True
   6252               Anniviers          Grimentz               Grimentz   1580.0     True
   6417       La Grande Béroche       Saint-Aubin     Saint-Aubin-Sauges    821.0     True
   6513                  Laténa             Marin                  Marin    456.0     True
    783               Hasliberg         Hasliberg              Hasliberg   1165.0     True
   6808           Clos du Doubs     Saint-Ursanne          Saint-Ursanne    445.0     True
   3714               Rheinwald           Splügen                Splügen   1462.0     True
   5409                   Ollon Villars-sur-Ollon      Villars-sur-Ollon   1250.0     True
   3292                   Flums       Flumserberg Flumserberg Tannenheim   1400.0     True
   6024                  Nendaz      Haute-Nendaz           Haute-Nendaz   1350.0     True
   3506             Vaz/Obervaz       Lenzerheide            Lenzerheide   1473.0     True
   6034                Orsières           Champex                Champex   1480.0     True
   2299               Plaffeien        Schwarzsee             Schwarzsee   1026.0     True
    843                  Saanen            Gstaad                 Gstaad   1055.0     True
    584           Lauterbrunnen            Wengen                 Wengen   1272.0     True

### Korrekturen übernehmen

In [12]:
gem_k = gem.merge(korr_geo, on="bfs_nr", how="left")
m = gem_k["lat_k"].notna()
for a, b in [("lat", "lat_k"), ("lon", "lon_k"), ("hoehe_m", "hoehe_k"), ("ort_gefunden", "ort_k")]:
    gem_k.loc[m, a] = gem_k.loc[m, b]
gem_k["korrigiert"] = m
gem_k = gem_k.drop(columns=["lat_k", "lon_k", "hoehe_k", "ort_k", "kt_ok_k"])
print("korrigiert:", gem_k["korrigiert"].sum(), "| noch ohne Koordinaten:", gem_k["lat"].isna().sum())

korrigiert: 34 | noch ohne Koordinaten: 0

### Höhenklassen bilden und Gemeinde-Stammdaten speichern

In [13]:
   def klasse(h):
       return "tief" if h < 1000 else ("mittel" if h <= 1500 else "hoch")

   gem_k["hoehenklasse"] = gem_k["hoehe_m"].apply(klasse)
   print(gem_k["hoehenklasse"].value_counts())

   gem_k["kanton"] = gem_k["kanton_geo"].fillna(gem_k["kt_hint"])
   out = gem_k[["bfs_nr", "name", "kanton", "lat", "lon", "hoehe_m", "hoehenklasse", "ort_gefunden", "korrigiert"]]
   out.to_csv("../data/processed/gemeinden.csv", index=False)

hoehenklasse
tief      134
mittel     39
hoch       13
Name: count, dtype: int64

### Restliche Gemeinden anhand API suchen: Test

In [15]:
liste = gem_k.sort_values("hoehe_m")[["bfs_nr", "name", "ort_gefunden", "kanton_geo", "hoehe_m", "n_treffer", "kt_ok", "korrigiert"]]
liste.to_csv("../data/processed/gemeinden_liste.txt", sep="|", index=False)
print(len(liste))

186